<?php

namespace Tests\Unit;

use Easi\DB2\Database\DB2Connection;
use Easi\DB2\Database\Schema\Blueprint;
use LogicException;
use Tests\Unit\Helpers\FakePDO;

function blueprintTestConnection(): DB2Connection
{
    $connection = new DB2Connection(new FakePDO(), 'TESTDB', '', [
        'driver' => 'db2_ibmi_odbc',
        'schema' => 'test',
    ]);

    $connection->useDefaultSchemaGrammar();

    return $connection;
}

describe('compileCreate', function () {
    // $systemName is optional; before it defaulted to null, reading an uninitialized
    // typed property made every create without forSystemName() fatal.
    it('compiles a create table when no system name was given', function () {
        $connection = blueprintTestConnection();

        $blueprint = new Blueprint($connection, 'products', function (Blueprint $table) {
            $table->create();
            $table->string('sku', 20);
        });

        expect($blueprint->toSql())->toBe(['create table products (sku varchar(20) not null)']);
    });

    it('appends the system name when one was given', function () {
        $connection = blueprintTestConnection();

        $blueprint = new Blueprint($connection, 'products', function (Blueprint $table) {
            $table->forSystemName('PRODS');
            $table->create();
            $table->string('sku', 20);
        });

        expect($blueprint->toSql())->toBe(['create table products for system name PRODS (sku varchar(20) not null)']);
    });
});

describe('modifyIncrement', function () {
    it('makes a lone identity column the primary key', function () {
        $blueprint = new Blueprint(blueprintTestConnection(), 'products', function (Blueprint $table) {
            $table->create();
            $table->bigIncrements('id');
        });

        expect($blueprint->toSql()[0])->toContain('primary key');
    });

    it('keeps the identity but drops the primary key when opted out with withoutPrimaryKey()', function () {
        $blueprint = new Blueprint(blueprintTestConnection(), 'products', function (Blueprint $table) {
            $table->create();
            $table->bigIncrements('id')->withoutPrimaryKey();
        });

        $sql = $blueprint->toSql();

        expect($sql[0])->toContain('generated by default as identity')
            ->and($sql[0])->not->toContain('primary key')
            ->and($sql[0])->not->toContain('constraint');
    });

    // Adding a bare identity column to an existing table, keyed by a unique index instead.
    it('adds an identity column to an existing table without a primary key', function () {
        $blueprint = new Blueprint(blueprintTestConnection(), 'products', function (Blueprint $table) {
            $table->bigIncrements('id')->withoutPrimaryKey();
            $table->unique('id');
        });

        $sql = $blueprint->toSql();

        expect($sql[0])->toBe('alter table products add column id bigint not null generated by default as identity')
            ->and($sql[1])->toBe('alter table products add constraint products_id_unique unique(id)');
    });

    // An inline primary key plus an explicit primary() command is two primary keys on one
    // table, which DB2 rejects; the declared key wins.
    it('leaves the primary key to an explicit primary() command', function () {
        $blueprint = new Blueprint(blueprintTestConnection(), 'products', function (Blueprint $table) {
            $table->create();
            $table->bigIncrements('id');
            $table->string('sku', 20);
            $table->string('region', 2);
            $table->primary(['sku', 'region']);
        });

        $sql = $blueprint->toSql();

        expect($sql[0])->toContain('generated by default as identity')
            ->and($sql[0])->not->toContain('primary key')
            ->and($sql[1])->toContain('primary key (sku, region)');
    });
});

describe('compileDropIfExists', function () {
    it('compiles a native drop table if exists', function () {
        $connection = blueprintTestConnection();

        $blueprint = new Blueprint($connection, 'products', function (Blueprint $table) {
            $table->dropIfExists();
        });

        expect($blueprint->toSql())->toBe(['drop table if exists products']);
    });

    it('qualifies the table when a schema is given', function () {
        $connection = blueprintTestConnection();

        $blueprint = new Blueprint($connection, 'inventory.products', function (Blueprint $table) {
            $table->dropIfExists();
        });

        expect($blueprint->toSql())->toBe(['drop table if exists inventory.products']);
    });
});

describe('getReplyListSequenceNumber', function () {
    // Same uninitialized-typed-property hazard as $systemName, but here a silent default
    // would compile RMVRPYLE against the wrong entry, so fail loudly instead.
    it('fails with a clear message when no sequence number has been reserved', function () {
        $blueprint = new Blueprint(blueprintTestConnection(), 'products');

        expect(fn () => $blueprint->getReplyListSequenceNumber())
            ->toThrow(LogicException::class, 'No reply list sequence number has been reserved');
    });

    it('returns the reserved sequence number', function () {
        $blueprint = new Blueprint(blueprintTestConnection(), 'products');
        $blueprint->setReplyListSequenceNumber(42);

        expect($blueprint->getReplyListSequenceNumber())->toBe(42);
    });
});
